### PR TITLE
Fix obj::parse looping infinitely.

### LINKED ISSUE #62: obj::parse() never returns
Title. When I call obj::parse("thing.obj"), my code hangs forever at that line.

### PR DESCRIPTION
**Pull request by phaazon**
The fix was made possible by introducing the concept of parser
difference, which is simply computing how much of input data was
consumed between two parser states. Cloning a parser is a very
lightweiht operation as parsers are just borrowed input decorated with
some bytes tracking (usize). We can then easily observe if a successful
parser is successful because it just peeked without consuming anything,
which is a good sign of corrupted data.

In a better world, we should have more strict parsing, especially in
parse_geometries, which as a wildcard pattern-matching (that should be
removed and replaced with a strict alternative, IMHO).

Fixes #62

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -1,7 +1,6 @@
 //! Parsers for wavefront's `.obj` and `.mtl` file format for loading meshes.
 #![crate_type = "lib"]
 
-#![deny(warnings)]
```
Comment (phaazon) [inline src/lib.rs]: Oops, I shouldn’t have removed that.

**Comment by phaazon** [comment]
@bvssvni whom should I ask reviews for?

**Comment by bvssvni** [comment]
Looks good to me.

**Comment by phaazon** [comment]
Ok, I shall merge that then @bvssvni but I guess some integration tests wouldn’t hurt. 🙂

**Comment by bvssvni** [comment]
Merging.

**Comment by bvssvni** [comment]
Thanks!
